version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:10.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - node-10-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - node-10-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: node-10-dependencies-{{ checksum "package.json" }}

      # Run Tests
      - run: npm run test:coverage

      - codecov/upload:
          file: coverage/*.json
